# Generated by Django 2.2.7 on 2019-11-19 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_name', models.CharField(max_length=25, verbose_name='news name')),
                ('news_content', models.CharField(max_length=200, verbose_name='news content')),
                ('news_author', models.CharField(max_length=30, verbose_name='news author')),
                ('news_date', models.DateTimeField(verbose_name='news date')),
            ],
            options={
                'verbose_name_plural': 'news',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(max_length=30, verbose_name='last name')),
                ('phone_number', models.BigIntegerField(blank=True, null=True, verbose_name='phone number')),
                ('e_mail', models.EmailField(max_length=254, verbose_name='email address')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='students.Person')),
                ('group_id', models.CharField(max_length=10, verbose_name='group name')),
                ('study_year', models.SmallIntegerField(max_length=2, verbose_name='year of studying')),
            ],
            bases=('students.person',),
        ),
    ]
