# Generated by Django 2.1.1 on 2019-12-18 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_date',
            field=models.DateField(verbose_name='news date'),
        ),
    ]
