# Generated by Django 2.1.1 on 2019-12-18 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20191218_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_date',
            field=models.DateField(auto_now_add=True, verbose_name='news date'),
        ),
    ]
